version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    env_file: ./.env
    environment:
      - PORT=$NODE_PORT
    ports:
      - $NODE_PORT:$NODE_PORT
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    env_file: ./.env
    environment:
      - PORT=$MONGO_PORT
    ports:
      - $MONGO_PORT:$MONGO_PORT
    volumes:
      - ./data:/data/db
